Linux Kernel 3.10.82 compiles and runs (.rej kept because compile error)
Applied:
/LineageOS/android/kernel/sony/msm8994$ patch -p1 -R <
/home/dj/Downloads/linuxkernelpatches/patch-3.10.82-83

Compile error if fs/exec.c.rej implemented:
../../../../../../kernel/sony/msm8994/fs/exec.c: In function
'prepare_binprm':
../../../../../../kernel/sony/msm8994/fs/exec.c:1300:14: error: 'struct
task_struct' has no member named 'no_new_privs'
      !current->no_new_privs &&

Possible solution:
if (task_no_new_privs(current))

Change-Id: Ibd0f1e8e4721311d2236e5c6c863052065c2009c