Linux Kernel 3.10.104 compiles - .rej files
.rej files
Applied:
/LineageOS/android/kernel/sony/msm8994$ patch -p1 -R <
/home/dj/Downloads/linuxkernelpatches/patch-3.10.104-105

SOLVED blkcipher.c.rej , addrconf.c.rej because compile errors:

../../../../../../kernel/sony/msm8994/crypto/blkcipher.c: In function
'crypto_init_blkcipher_ops_async':
../../../../../../kernel/sony/msm8994/crypto/blkcipher.c:475:5: error:
'struct ablkcipher_tfm' has no member named 'has_setkey'
  crt->has_setkey = alg->max_keysize;
     ^
make[2]: ***
[/media/dj/6c6638f0-2a87-4474-b638-f8e8b4050bb3/LineageOS/android/kernel/sony/msm8994/scripts/Makefile.build:308:
crypto/blkcipher.o] Error 1
make[1]: ***
[/media/dj/6c6638f0-2a87-4474-b638-f8e8b4050bb3/LineageOS/android/kernel/sony/msm8994/Makefile:818:
crypto] Error 2

-------------------------

../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c: In function
'addrconf_rs_timer':
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c:3259:33:
error: 'lladdr' undeclared (first use in this function)
   if (!__ipv6_get_lladdr(idev, &lladdr, IFA_F_TENTATIVE))
                                 ^
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c:3259:33: note:
each undeclared identifier is reported only once for each function it
appears in
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c:3266:3: error:
implicit declaration of function 'addrconf_mod_rs_timer'
[-Werror=implicit-function-declaration]
   addrconf_mod_rs_timer(idev, (idev->rs_probes ==
   ^
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c: In function
'addrconf_dad_completed':
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c:3423:30:
error: 'lladdr' undeclared (first use in this function)
   if (!ipv6_get_lladdr(dev, &lladdr, IFA_F_TENTATIVE))
                              ^
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c: In function
'addrconf_cleanup':
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c:5392:23:
error: 'addr_chk_work' undeclared (first use in this function)
  cancel_delayed_work(&addr_chk_work);
                       ^
../../../../../../kernel/sony/msm8994/net/ipv6/addrconf.c:5395:20:
error: 'addrconf_wq' undeclared (first use in this function)

Change-Id: I29cffe6044babecf928746c54589a2b4bfcaec6f