Linux Kernel 3.10.55 compiles and runs (.rej cleaned up)
Applied:
/LineageOS/android/kernel/sony/msm8994$ patch -p1 -R <
/home/dj/Downloads/linuxkernelpatches/patch-3.10.55-56

1) mm/percpu-vm.c bugfixed because "populated" in the call is a
parameter too much:

In file included from
../../../../../../kernel/sony/msm8994/mm/percpu.c:827:0:
../../../../../../kernel/sony/msm8994/mm/percpu-vm.c: In function
'pcpu_alloc_pages':
../../../../../../kernel/sony/msm8994/mm/percpu-vm.c:95:35: error:
'populated' undeclared (first use in this function)
     pcpu_free_pages(chunk, pages, populated,
                                   ^
../../../../../../kernel/sony/msm8994/mm/percpu-vm.c:95:35: note: each
undeclared identifier is reported only once for each function it appears
in
../../../../../../kernel/sony/msm8994/mm/percpu-vm.c:95:5: error: too
many arguments to function 'pcpu_free_pages'
     pcpu_free_pages(chunk, pages, populated,

definition is:

static void pcpu_free_pages(struct pcpu_chunk *chunk,
			    struct page **pages, int page_start, int
page_end)

2) include/linux/sched.h not reverted because for_each_thread(p, t) used
in drivers/staging/android/lowmemorykiller.c and kernel/seccomp.c:

../../../../../../kernel/sony/msm8994/kernel/seccomp.c: In function
'seccomp_can_sync_threads':
../../../../../../kernel/sony/msm8994/kernel/seccomp.c:286:2: error:
implicit declaration of function 'for_each_thread'
[-Werror=implicit-function-declaration]
  for_each_thread(caller, thread) {
  ^
../../../../../../kernel/sony/msm8994/kernel/seccomp.c:286:34: error:
expected ';' before '{' token
  for_each_thread(caller, thread) {
                                  ^
../../../../../../kernel/sony/msm8994/kernel/seccomp.c: In function
'seccomp_sync_threads':
../../../../../../kernel/sony/msm8994/kernel/seccomp.c:327:34: error:
expected ';' before '{' token
  for_each_thread(caller, thread) {
                                  ^
../../../../../../kernel/sony/msm8994/kernel/seccomp.c: At top level:
../../../../../../kernel/sony/msm8994/kernel/seccomp.c:256:12: warning:
'is_ancestor' defined but not used [-Wunused-function]
 static int is_ancestor(struct seccomp_filter *parent,
            ^
../../../../../../kernel/sony/msm8994/kernel/seccomp.c: In function
'seccomp_can_sync_threads':
../../../../../../kernel/sony/msm8994/kernel/seccomp.c:308:1: warning:
control reaches end of non-void function [-Wreturn-type]

-----------

../../../../../../kernel/sony/msm8994/drivers/staging/android/lowmemorykiller.c:
In function 'test_task_flag':
../../../../../../kernel/sony/msm8994/drivers/staging/android/lowmemorykiller.c:196:2:
error: implicit declaration of function 'for_each_thread'
[-Werror=implicit-function-declaration]
  for_each_thread(p, t) {
  ^
../../../../../../kernel/sony/msm8994/drivers/staging/android/lowmemorykiller.c:196:24:
error: expected ';' before '{' token
  for_each_thread(p, t) {
                        ^
../../../../../../kernel/sony/msm8994/drivers/staging/android/lowmemorykiller.c:206:1:
warning: no return statement in function returning non-void
[-Wreturn-type]

Change-Id: Ifbc072edf15bc19225a439945b8b6dcdb59499be