Linux Kernel 3.10.47 compiles and runs (.rej cleaned up)
Applied:
/LineageOS/android/kernel/sony/msm8994$ patch -p1 -R <
/home/dj/Downloads/linuxkernelpatches/patch-3.10.47-48

Bugfix of a revert in drivers/usb/gadget/f_fs.c because it is creating a
build error:

In file included from
../../../../../../kernel/sony/msm8994/drivers/usb/gadget/android.c:55:0:
../../../../../../kernel/sony/msm8994/drivers/usb/gadget/f_fs.c: In
function 'functionfs_bind':
../../../../../../kernel/sony/msm8994/drivers/usb/gadget/f_fs.c:1489:12:
error: 'first_id' undeclared (first use in this function)
   int id = first_id;

Bugfix:

@@ -1486,7 +1486,7 @@ static int functionfs_bind(struct ffs_data *ffs,
struct usb_composite_dev *cdev)
 	lang = ffs->stringtabs;
 	for (lang = ffs->stringtabs; *lang; ++lang) {
 		struct usb_string *str = (*lang)->strings;
-		int id = first_id;
+		int id = ffs->first_id;
 		for (; str->s; ++id, ++str)
 			str->id = id;
 	}

Change-Id: Ie8a9e0252b1d3a65dcc482761f358ed545c21ee8