Linux Kernel 3.10.40 compiles and runs (.rej cleaned up)
Applied:
/LineageOS/android/kernel/sony/msm8994$ patch -p1 -R <
/home/dj/Downloads/linuxkernelpatches/patch-3.10.40-41

Bugfix in revert:
include/linux/list.h not reverted since list_next_entry() is needed:
--------------------------------
../../../../../../kernel/sony/msm8994/drivers/crypto/msm/qcrypto.c: In
function '_qcrypto_static_assign_engine':
../../../../../../kernel/sony/msm8994/drivers/crypto/msm/qcrypto.c:1970:3:
error: implicit declaration of function 'list_next_entry'
[-Werror=implicit-function-declaration]
   cp->next_engine = list_next_entry(pengine, elist);
   ^
../../../../../../kernel/sony/msm8994/drivers/crypto/msm/qcrypto.c:1970:46:
error: 'elist' undeclared (first use in this function)
   cp->next_engine = list_next_entry(pengine, elist);

Change-Id: I402fc9accee1d28a8ce7f36e0c7bfc11ef19951d